version: '3'

services:
  db:
    image: postgres:16
    expose:
      - 5432
    #volumes:
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
